#ifndef SHANDALAR_INTERNAL_H
#define SHANDALAR_INTERNAL_H

#include <windows.h>
#include <stdio.h>
#include <setjmp.h>
#include "defs.h"
#include "shandalar.h"
#include "facemaker/src/facemaker_types.h"
#include "drawcardlib/src/pic.h"
#include "deckdll/src/magsnd.h"

typedef struct
{
  int first;
  int second;
} HintPair;

typedef union
{
  struct
  {
    EncodedImage *normal[12];
    EncodedImage *highlight[12];
    EncodedImage *pressed[12];
    EncodedImage *icon[12];
  } named;
  EncodedImage *by_group[4][12];
} WorldMagicChoiceButtonSpriteBank;

typedef struct
{
  EncodedImage *frame[4][9];
  EncodedImage *icon_rows[4][4];
} DialogBoxSpriteBank;

typedef struct
{
  char samples[0x13][0x13];
  char padding[7];
} AnimatedNoiseGridPlane;

int HandleMainMenuButtonControlEvent(AdvMenuControl *control_ptr, int event_type);
int HandlePortraitMainMenuControlEvent(AdvMenuControl *control_ptr, int event_type);
int HandleWorldMagicChoiceControlEvent(AdvMenuControl *control_ptr, int event_type);
int ActivateWorldMagicChoiceControl(AdvMenuControl *control);
int ActivateMainMenuControl(AdvMenuControl *control);

extern HDC global_main_hdc;
extern int global_screen_width;
extern int global_screen_height;
extern int g_neighbor_dx[9];
extern int g_neighbor_dy[9];
extern char *PTR_s_advinter800_pic_00589de8;
extern FacemakerWindowBounds g_page0_window_bounds_storage;
extern FacemakerWindowBounds *g_page0_window_bounds;
extern FacemakerWindowBounds g_page1_window_bounds_storage;
extern FacemakerWindowBounds *g_page1_window_bounds;
extern FacemakerWindowBounds g_page2_window_bounds_storage;
extern FacemakerWindowBounds *g_page2_window_bounds;
extern FacemakerWindowBounds g_page3_window_bounds_storage;
extern FacemakerWindowBounds *g_page3_window_bounds;
extern FacemakerWindowBounds g_page5_window_bounds_storage;
extern FacemakerWindowBounds *g_page5_window_bounds;
extern HINSTANCE g_app_instance;
extern int g_skip_world_sfx_preload;
extern int g_loadsave_skip_esc;
extern UINT g_timer_resolution_ms;
extern UINT g_timer_event_handle;
extern int g_cursor_visibility_depth;
extern UINT g_timer_period_ms;
extern int g_ui_tick_count;
extern int g_default_palette_fade_steps;
extern int g_sound_loader_busy;
extern HANDLE g_main_thread_handle;
extern HANDLE g_timer_thread_handle;
extern int g_local_sound_missing;
extern int g_local_sound_state;
extern HANDLE g_loader_thread_handle;
extern int g_palette_class_registered;
extern int g_timer_thread_handle_ready;
extern HWND g_palette_window_hwnd;
extern int g_mouse_button_down_mask;
extern int g_mouse_y;
extern int g_mouse_x;
extern int g_mouse_button_released_mask;
extern int g_cached_cwd_initialized;
extern int g_sound_drive_initialized;
extern char g_cached_cwd[0x100];
extern char g_sound_drive_letter;
extern char *g_advblocks_file_buffer;
extern FILE *g_advbuttons_ini_file;
extern char g_ini_string_scratch[0x28];
extern char *g_done_text_table_entry;
extern int g_legacy_mouse_active;
extern int g_hide_world_map_overlays;
extern EncodedImage *g_ttsprite_special_sprite_a;
extern EncodedImage *g_world_magic_avatar_sprites[5];
extern EncodedImage *g_face_preview_sprite_selected;
extern EncodedImage *g_face_preview_sprite_group[6];
extern int g_world_scene_reveal_effect_pending;
extern int g_world_location_entry_enabled;
extern int g_world_move_dir_index;
extern int g_world_location_music_active;
extern int g_world_location_music_track_id;
extern int g_world_location_music_town_index;
extern int g_world_magic_town_flags[5];
extern int g_world_player_animation_direction;
extern int g_world_player_animation_frame;
extern int g_world_location_entry_latched;
extern int g_advfac64_load_state;
extern int g_adventure_demo_enabled;
extern int g_adventure_demo_idle_ticks;
extern int g_world_scene_force_redraw;
extern int g_deck_total_card_count;
extern int g_deck_active_card_count;
extern long g_hint_text_offsets[0x100];
extern int g_hint_difficulty_masks[0x100];
extern char g_last_parsed_deck_path[0x110];
extern HintPair g_hint_card_pairs[0x100];
extern int g_mouse_x_snapshot;
extern int g_mouse_y_snapshot;
extern int g_mouse_button_mask_snapshot;
extern DialogBoxSpriteBank g_dialog_box_sprite_bank;
extern HANDLE g_statwin_dll_module;
extern int g_dungeon_card_effect_by_color[4];
extern int g_dungeon_card_effect_by_monster_flags[9];
extern int g_mana_castle_card_effect_by_difficulty[5][4];
extern int g_statwin_exports_by_ordinal[3];
extern int g_menu_render_guard;
extern AnimatedNoiseGridPlane g_animated_noise_grid[2];
extern FacemakerWindowBounds g_menu_saved_window_bounds;
extern int g_menu_control_count_by_context[50];
extern AdvMenuControl *g_menu_controls_by_context[50][50];
extern EncodedImage *g_main_menu_button_sprites_normal[4];
extern EncodedImage *g_main_menu_button_sprites_highlight[4];
extern WorldMagicChoiceButtonSpriteBank g_world_magic_choice_button_sprite_bank;
extern EncodedImage *g_road_sprite_entries[0xc];
extern EncodedImage *g_location07_sprite_entries[0xc];
extern EncodedImage *g_land_sprite_entries[22][5];
extern EncodedImage *g_tsprite2_grid_sprite_entries[0xc];
extern EncodedImage *g_land_tile_sprite_entries[0x10];
extern EncodedImage *g_ttsprite_alt_sprite_entries[8];
extern EncodedImage *g_cstline1_sprite_entries[12][7];
extern EncodedImage *g_ttsprite_aux_sprite_entries[8];
extern int g_world_lair_monster_sprite_top_clips[0x10];
extern int g_ego_sprite_draw_height;
extern int g_sego_sprite_draw_height;
extern EncodedImage *g_location_marker_sprite_entries[0x9e];
extern EncodedImage *g_questnew_sprite_entries[4];
extern EncodedImage *g_asprite_sprite_entries[0x3c];
extern EncodedImage *g_tsprite2_extra_sprite_entries[0xd];
extern EncodedImage *g_gsprite_sprite_entries[3];
extern EncodedImage *g_sunmoon_sprite_entries[0x14];
extern EncodedImage *g_worlds_extra_sprite_entries[4];
extern EncodedImage *g_tips_frame_sprite;
extern EncodedImage *g_clocknew_sprite_entries[9];
extern EncodedImage *g_tips_icon_sprite;
extern EncodedImage *g_wizard_controlled_town_sprite_entries[5];
extern EncodedImage *g_sland_sprite_entries[22][5];
extern EncodedImage *g_daysnew_sprite_entries[0xc];
extern EncodedImage *g_icons_sprite_entries[0x18];
extern int g_world_lair_monster_sprite_widths[0x10];
extern int g_ego_sprite_width;
extern int g_sego_sprite_width;
extern int g_world_lair_monster_sprite_heights[0x10];
extern int g_ego_sprite_height;
extern int g_sego_sprite_height;
extern EncodedImage *g_ttsprite_special_sprite_b;
extern EncodedImage *g_ttsprite_special_sprite_c;
extern EncodedImage *g_current_location_marker_sprite;
extern EncodedImage *g_compnew_sprite_entries[5];
extern EncodedImage *g_endtop_banner_sprite;
extern EncodedImage *g_tsprite2_overlay_sprite_entries[8];
extern EncodedImage *g_ttsprite_grid_sprite_entries[0x40];
extern EncodedImage *g_castles_sprite_entries[20];
extern OpeningMenuSpriteWorkEntry g_opening_menu_sprite_work_buffer[0x20];
extern EncodedImage *g_ttsprite_extra_sprite_entries[10];
extern int g_menu_context_index;
extern AdvMenuControl g_main_menu_controls[4];
extern AdvMenuControl g_world_magic_choice_controls[5];
extern FacemakerWindowBounds *g_menu_control_draw_target_page;
extern int g_world_magic_icon_rect_table_padding;
extern AdvMenuRect g_world_magic_icon_rects[0xc];
extern char *g_world_magic_sound_paths[5];
extern int g_menu_current_control_index;
extern int g_menu_prev_control_index;
extern int g_menu_input_unhandled;
extern int g_menu_allow_arrow_nav_by_context[50];
extern int g_duel_special_rules_by_color[7];
extern jmp_buf g_adventure_session_restart_jump_buffer;
extern jmp_buf g_adventure_world_exit_jump_buffer;
extern int g_pending_world_location;
extern int g_current_world_location;
extern int g_adventure_ui_layout_dirty;
extern int g_adventure_ui_edge_pages_initialized;
extern int g_world_scroll_cache_ready;
extern int g_pending_ui_action_code;
extern int g_text_menu_left;
extern int g_text_menu_top;
extern int g_text_menu_initial_selection;
extern int g_text_menu_mouse_released;
extern int g_text_menu_last_selection;
extern int g_text_menu_show_ok_button;
extern int g_text_menu_mouse_active;
extern int g_text_menu_timeout_seconds;
extern int g_text_menu_line_height;
extern int g_text_menu_color_normal;
extern int g_text_menu_color_selected;
extern int g_text_menu_line_offsets[0x20];
extern int g_text_menu_color_base;
extern int g_text_menu_finish_flash;
extern int g_text_menu_line_count;
extern int g_text_menu_hovered_selection;
extern char g_text_menu_timer_itoa_buffer[0xc];
extern int g_shandalar_state_00789934;
extern signed char g_text_menu_hotkey_by_option[0x20];
extern int g_text_menu_caret_prefix_mask;
extern int g_text_menu_force_cancel;
extern int g_text_menu_needs_layout;
extern int g_text_menu_abort_requested;
extern int g_text_menu_option_count;
extern int g_text_menu_right;
extern int g_text_menu_max_line_width;
extern int g_text_menu_ok_mode;
extern int g_text_menu_first_option_line;
extern int g_text_box_frame_color_override;
extern int g_text_menu_disabled_option_mask;
extern int g_shandalar_state_005aa414;
extern int g_last_matching_deck_card_index;
extern int g_shandalar_initialized;

extern DIBSurface *g_graphics_pages[10];
extern char g_ui_message_buffer[0x1000];
extern int g_adventure_world_exit_requested;
extern unsigned int g_load_menu_valid_slot_mask;
extern char g_save_file_path[13];
extern int g_selected_save_slot_index;
extern int g_reveal_all_world_info;
extern int g_world_player_tile_x;
extern int g_world_player_tile_y;
extern char *global_base_txt;
extern HPALETTE global_cart_art_hpalette;
extern HPALETTE g_palette_handle;
extern int Gold;
extern int g_graphics_bpp;
extern RpBitsPalettePacket g_palette_data_words;
extern FontSlot g_font_slots[0x10];
extern int g_key_input_queue_count;
extern unsigned int g_key_input_queue[50];
extern int g_menu_selection_value;
extern int g_color_menu_selection_to_deck_color[5];
extern card_data_t global_cards_data[];
extern DIBSurface *g_facemaker_page4_dib;
extern HBITMAP g_facemaker_page4_bitmap;
extern int g_frontbuffer_direct_blit_enabled;

int InitLicenseSecretsFromRegistry(void);
int LoadAdvStringsFile(const char *filename);
int LoadTextSectionStringTable(const char *filename, const char *section, char **out_table, int max_entries, char *string_buf,
                               char *string_buf_end, char **out_next_buf);
int LoadAdvBlocksFile(const char *filename);
int FindNextTextBlock(char *scan_start, char *scan_end, int *out_block_start, int *out_next_scan);
void ReadCsvFieldByCsvid(char *out, int csvid, int field, const char *csv_name);
void *CreateGraphicsPage(int page_number, int width, int height, int bits_per_pixel);
void PreloadWorldAmbientSounds(void);
void FreeAdvblocksFileBuffer(void);
void QueueKeyInputFromMessage(WPARAM wparam, LPARAM lparam);
ATOM RegisterPaletteClass(HINSTANCE hinst);
HWND CreatePalettePopupWindow(HINSTANCE hinst, HWND parent_hwnd);
char **LoadIniEscapedStringTable(FILE *ini_file, char *section_name, char *scratch, ...);
int MeasureMultilineTextWidth(FacemakerWindowBounds *window_bounds, char *text);
int SetFontStyleSize(int font_id, unsigned int style);
void LoadPcxIntoPageNoPalette(char *path);
void ClearGraphicsPageWithPaletteColor(int page_number, int color_index);
void CopyGraphicsRect(FacemakerWindowBounds *src, int src_x, int src_y, unsigned int width, int height,
                      FacemakerWindowBounds *dst, int dst_x, int dst_y);
AdvMenuRect *PushGraphicsClipRect(AdvMenuRect *saved_clip_rect, FacemakerWindowBounds *page, int x, int y, int width, int height);
void BeginSpriteEncodeSession(void);
EncodedImage *EncodeSpriteFromPage(int page_number, int x, int y, int width, int height);
void FinalizeSpriteEncodeSession(void);
int DrawTextFormatted(FacemakerWindowBounds *dst, int text_color, int draw_shadow, int scale_to_screen, int center_x, int center_y, int x,
                      int y, int *format_and_args);
void ReadGraphicsScanline(unsigned int *out_scanline, int page_number, int src_x, int src_y, unsigned int byte_count);
void PlaySoundEffectOnChannel(char *sound_path, int channel, int volume, int pitch_percent, int pan_percent);
void PutGraphicsPixel(FacemakerWindowBounds *window_bounds, int x, int y, int color_index);
unsigned int ReadGraphicsPixel(int page_number, int x, int y);
void BlitGraphicsRect(FacemakerWindowBounds *dst, unsigned int dst_x, int dst_y, unsigned int width, DWORD height,
                      FacemakerWindowBounds *src, int src_x, int src_y);
void DrawEncodedImageResampled(FacemakerWindowBounds *dst, int x, int y, int width, int height, EncodedImage *encoded_image);
void StretchBlitGraphicsRect(FacemakerWindowBounds *dst, int dst_x, int dst_y, int src_w, int src_h,
                             FacemakerWindowBounds *src, int src_x, int src_y, int copy_w, int copy_h);
int IgnoreFontConfigLoadResult(int ignored_result);
int InitializeLegacyMouseStub(void);
int ShutdownLegacyMouseStub(void);
void *InitializeGraphicsSystemDefaultMode(void);
void SetGraphicsPage(int page_number, void *page);
void PresentGraphicsPage(int page_number);
void ReadPalette(char *palette_text_path, char *palette_binary_path);
int ScaleUiCoordinate(int value);
int LoadFontConfigIfPresent(char *executable_name, char *config_name);
int LoadSystemFont(int font_id, unsigned int point_size, char *font_file, char *font_name, int weight, DWORD italic);
int RunAdventureSession(void);
BOOL UnloadFontSlot(int font_slot);
int FileExists(const char *filename);
char FindDriveWithAsset(char *filename);
char GetSoundAssetDriveLetter(void);
unsigned int LoadSoundWithDriveFallback(char *filename, int channel, Sound *sound);
LONG ChangeDisplayResolution(DWORD width, DWORD height);
void RestoreDisplayResolution(void);
DWORD AdventureWorkerThread(LPVOID);
void NoopSetSpecialSprite(int unused_a, int unused_b, int unused_c);
char *BuildResolutionSpritePath(char *sprite_filename);
int ReadSpriteEntryPointersWithLimit(EncodedImage **out_entries, char *path, int max_entries);
void LoadTownHintMetadata(void);
void LoadCardRaritiesAndCsvOffsets(void);
void ShowMouseCursorNested(void);
void HideMouseCursorNested(void);
void ShowMouseCursor(void);
void HideMouseCursor(void);
int ReadSpriteEntryPointers(EncodedImage **out_sprite_entries, char *sprite_path);
void FreeSpriteBlob(void *memory);
void AnimatePaletteToColor(int color_index, int palette_id);
int RunOpeningMenu(void);
int RunDifficultyMenu(void);
int RunColorMenu(void);
int RunFacemakerFlow(void);
void InitializeNewGameState(void);
void GenerateAdventureWorldMap(void);
void InitializeAnimatedNoiseGrid(void);
int CalculateWorldTerrainValue(int x, int y);
void PropagatePathConnectivity(void);
int GenerateWorldTownSlots(void);
void GenerateTownConnections(void);
int CreateTownConnectionPath(int start_x, int start_y, int target_x, int target_y);
void FloodFillPathConnectivity(int x, int y, unsigned int depth);
void InitializeCastleDungeonSlots(void);
unsigned int GetWorldTileType(int x, int y);
unsigned int GetWorldTileMagicMask(unsigned int tile_type);
unsigned int GetWorldMapPixelFlags(int x, int y);
void SetWorldMapPixelFlags(unsigned int mask, int x, int y);
void ClearWorldMapPixelFlags(unsigned int mask, int x, int y);
void MarkPathConnection(int x, int y, int direction_index);
int SampleAnimatedNoiseGridBilinear(int x_fixed, int y_fixed);
void SaveGameToSlot(int save_slot_index);
int RunLoadGameMenu(void);
int load_selected_duel_save_slot(int save_slot_index);
int single_color_test_bit_to_color_t(int mask);
void AddJournalEntry(int entry_type, int entry_arg);
int LoadStatWinDllExports(void);
void LoadOpeningMenuSpriteResources(void);
int RenderAdvMenuControlDisabled(AdvMenuControl *control);
int InitializeMainMenuAndWorldMagicChoiceControls(void);
void UpdateWorldMagicUnlockProgress(void);
void RebuildDeckEntriesByCardGroup(void);
void RefreshAdventureInterfaceLayout(void);
int ConsumeUiTickCount(void);
void RenderAdventureWorldScene(int world_x, int world_y, int world_state);
int RunRightClickMenuAndQueueInput(void);
int QueuePendingMenuActionInput(void);
void UpdateAdventureWorldInputAndMovement(void);
void UpdateWorldLairAndMonsterSlots(void);
void TickWorldMagicSlotTimers(void);
void UpdateMouseSnapshot(void);
int BeginMenuContext(void);
int ResetMenuContext(int context_index);
int AddMenuControlsToContext(AdvMenuControl *controls, int control_count, int context_index);
int EndMenuContext(void);
int FadeInPaletteFromGray(int gray, int steps);
void DrawFormattedTextShadowedCenterY(FacemakerWindowBounds *window, int color_index, int x, int y, char *format, ...);
void DrawFormattedTextShadowedCentered(FacemakerWindowBounds *window, int color_index, int x, int y, char *format, ...);
void DrawFormattedTextShadowed(FacemakerWindowBounds *window, int color_index, int x, int y, char *format, ...);
void LoadPcxIntoPageOpaque(int page_number, char *path);
int ExportGraphicsPage(int page_number, char *path);
int ExportEncodedImage(int page_number, int x, int y, int width, int height, int write_palette, char *path);
unsigned int WaitForInputEventUnlessBlocked(void);
int UpdateMenuControlSelection(int mouse_x, int mouse_y, int allow_activate_on_click);
unsigned int PeekQueuedKeyInput(void);
unsigned int WaitForInputEvent(void);
int ApproximateDistance(int delta_x, int delta_y);
void ClearInputAndWaitForMouseRelease(void);
void ClearQueuedKeyInput(void);
void UnloadStatWinDllExports(void);
int HasQueuedKeyInput(void);
int PopQueuedKeyInput(void);
int PopNormalizedQueuedKeyInput(void);
void destroy_create_fonts_resources(void);
void FillGraphicsRect(FacemakerWindowBounds *window_bounds, int x, int y, int width, int height, unsigned int color_index);
unsigned int __cdecl save_or_load_ver1(void);
void BuildFacemakerPortraitSprites(FacemakerWindowBounds *page);

#ifdef _DEBUG
void RunLairExplorationEvent(int color);
#endif

void DelayUiTicks(int ticks);
int find_internal_card_id_by_csv_id(card_id_t card_id);
unsigned int PickRandomColorBitExcludingMask(unsigned int excluded_mask);
int AddRandomStarterDeckCards(unsigned int color_mask, int land_count, int spell_count, int creature_count, int add_rare, int allow_artifact_spells);
int PickRandomCardMatchingTypeAndColor(unsigned int type_mask, unsigned int color_mask);
int AddCardToDeckSorted(int card_id);
int GetCardRarity(int card_id);
int GetRemainingAllowedCardCopies(unsigned int card_id);
unsigned int GetGraphicsPixelColorRef(FacemakerWindowBounds *window, int x, int y);
int RunLoadSaveMenu(int save_mode);
int UpdateStatWindowProgress(void *progress_values);
int MapWizardColorToDisplayIndex(int wizard_color);
int ConsumeMouseButtonReleaseMask(void);
int RunTextMenuAt(char *menu_text, int left_x, int top_y);
int RunTextMenuCore(char *menu_text, int clear_input_before_show);
int RunTextMenuAtScaled(char *menu_text, int x_320_scale, unsigned int y_200_scale);
int DrawTextMenu(char *menu_text, int selected_option);
void DrawDialogBoxFrameAutoStyle(int x, int y, int width, int height, int unk1);
void DrawRectangleBorder(int x, int y, int width, int height, int color_index);
void DrawTiledDialogBoxFrame(int x, int y, int width, int height, int frame_style);
void DrawUiLine(int x1, int y1, int x2, int y2, int color_index);
void DrawTextLineClamped(char *text, int x, int y, int color_index);
void DrawTextLineNoShadow(char *text, int x, int y, int color_index);
void DrawCenteredTextLineClamped(char *text, int center_x, int y, int color_index);
int MeasureTextLineWidth(char *text);
void DrawEncodedImageUiScaled(FacemakerWindowBounds *dst, int x_320, int y_200, EncodedImage *sprite, int width_320, int height_200);
int FindWorldMagicCardIndex(int world_magic_slot_index);
void PushQueuedKeyInput(int key_code);
int MapWorldClickToMovementKey(int x, int y);
int RenderMenuControlRange(int first_index, int count);
int GetUiTickCount(void);
int SeedRandomFromTickCount(void);
int ClampIntToRange(int value, int min_value, int max_value);
int int_to_hex_digit(int value);
unsigned int load_or_probe_duel_save_slot(char *save_file_path, int validate_only);
int SaveGameWithMessage(char *save_file_path);
int GetSaveDriveIndex(void);
int IsSaveDriveAvailable(int drive_index);
int LoadGameFromPath(char *save_file_path);
int SaveGameToPath(char *save_file_path);
int GetFontCharWidth(int font_slot, char ch);
int GetFontLineHeight(int font_slot);
void DrawGraphicsLine(FacemakerWindowBounds *window_bounds, int x1, int y1, int x2, int y2, int color_index);
int DrawTextLine(FacemakerWindowBounds *window_bounds, int x, int y, char *text);
void DrawEncodedImageUnscaled(FacemakerWindowBounds *dst, int x, int y, EncodedImage *encoded_image);
void DrawTextAt(FacemakerWindowBounds *window, int color, int x, int y, char *text, ...);
WPARAM WINAPI DeckBuilderMain(HWND parent_hwnd, int db_flags_1, int db_flags_2);
int LoadTextSectionLines(const char *filename, const char *section);
int IsKeyInputQueueEmpty(void);
unsigned int WorldRoadTileHasDirection(int tile_x, int tile_y, int direction_index);
int FreeOpeningMenuSpriteWorkEntries(int work_entry_index_a, int work_entry_index_b);
int SignNonZero(int value);
int RestoreAdventureUiPaletteAndFocus(void);
int VisitTownSlot(int town_index);
int RunSaveMenuAndSelectSlot(void);
void *DrawAdventureInterfaceLayout(int force_redraw);
int RunRandomAiDuelDemo(void);
void EnsureAdvfac64Loaded(int state);
void StartWizardTownSiege(void);
void ResolveWizardTownSiege(void);
void PlaySoundWithPitchAndPan(int sound_id, int volume, int pitch_percent, int pan_percent);
void PlayLoopingSoundWithPan(int sound_id, int volume, int pan_percent);
void LoadLoopingSound(char *sound_path, int channel);
void UpdateAmbientWizardColorSound(int wizard_color);
void EnterCastleDungeon(int dungeon_index);
void ShowCityInfoScreen(int unused);
void ShowDungeonCluesScreen(int unused);
int RunAdventureStatsMenu(void);
void ShowWorldMapScreen(int mode);
int ShowStatsWindow(int mode, int highlight);
void AnalyzeDeckAndMaybeShowReport(int show_ui);
int FindTownAtWorldCoordinates(int world_x, int world_y);
int FindCastleDungeonAtWorldCoordinates(int world_x, int world_y);
extern int g_world_player_tile_x;
extern int g_world_player_tile_y;
extern char *global_base_txt;
extern HPALETTE global_cart_art_hpalette;
extern HPALETTE g_palette_handle;
extern int Gold;
extern int g_graphics_bpp;
extern RpBitsPalettePacket g_palette_data_words;
extern FontSlot g_font_slots[0x10];
extern int g_key_input_queue_count;
extern unsigned int g_key_input_queue[50];
extern int g_menu_selection_value;
extern int g_color_menu_selection_to_deck_color[5];
extern card_data_t global_cards_data[];
extern DIBSurface *g_facemaker_page4_dib;
extern HBITMAP g_facemaker_page4_bitmap;
extern int g_frontbuffer_direct_blit_enabled;

void ClearAndLoadInitialLibraryFromDeckFile(char *deck_path, int library_index, unsigned int color_filter, int speed_filter);
int RunDuelEngine(unsigned int card_id, int creature_type);


#endif
