#include "magic_shell_screen_name.h"
#include "magic_sealed_open_packs.h"
#include <string.h>

// FUNCTION: MAGIC 0x0048ec81
void shell_layout_screen_name_dialog(HWND hwnd)
{
  struct
  {
    char label_text[100];
    HWND control;
    RECT control_rect;
    int secondary_y;
    HDC dc;
    int control_height;
    RECT stats_icon_rect;
    int control_width;
    int y;
    int edit_height;
    int x;
    int character_width;
    int secondary_x;
    HGDIOBJ font;
    RECT portrait_rect;
    RECT client_rect;
    SIZE text_size;
    int button_height;
    int line_height;
    int spacing;
  } s;
  GetClientRect(hwnd, &s.client_rect);
  s.client_rect.left += 0x14;
  s.client_rect.right += -0x14;
  s.client_rect.top += 0x14;
  s.client_rect.bottom += -0x14;
  s.font = (HGDIOBJ)SendDlgItemMessageA(hwnd, 0x70c, 0x31, 0, 0);
  s.dc = GetDC(hwnd);
  SelectObject(s.dc, s.font);
  GetTextExtentPoint32A(s.dc, "fun", 3, &s.text_size);
  s.button_height = s.text_size.cy * 2;
  s.line_height = s.text_size.cy;
  s.edit_height = (s.text_size.cy * 3) / 2;
  s.spacing = (s.text_size.cy * 3) / 2;
  GetTextExtentPoint32A(s.dc, "m", 1, &s.text_size);
  s.character_width = s.text_size.cx;
  s.x = 0;
  s.y = 0;
  SetRect(&s.control_rect, 0, 0, s.client_rect.right / 4, s.client_rect.bottom - s.button_height * 3);
  shell_fit_sealed_pack_rect(&s.portrait_rect, &s.control_rect, 0x8a, 0xaa);
  s.control_width = (s.portrait_rect.right - s.portrait_rect.left) + 4;
  s.control_height = (s.portrait_rect.bottom - s.portrait_rect.top) + 4;
  s.portrait_rect.top = 0;
  s.portrait_rect.bottom = s.portrait_rect.top + s.control_height;
  s.portrait_rect.left = 0;
  s.portrait_rect.right = s.portrait_rect.left + s.control_width;
  s.control = GetDlgItem(hwnd, 0x715);
  SetWindowPos(s.control, NULL, s.portrait_rect.left, s.portrait_rect.top,
      s.portrait_rect.right - s.portrait_rect.left, s.portrait_rect.bottom - s.portrait_rect.top, 4);
  SetRect(&s.control_rect, 0, 0, 0x2d, 0x2d);
  shell_fit_sealed_pack_rect(&s.stats_icon_rect, &s.control_rect, 0x3c, 0x3c);
  s.stats_icon_rect.top = s.client_rect.top;
  s.stats_icon_rect.left = s.client_rect.right + -0x3c;
  s.stats_icon_rect.right += 5;
  s.stats_icon_rect.bottom += 5;
  s.control = GetDlgItem(hwnd, 0x743);
  SetWindowPos(s.control, NULL, s.stats_icon_rect.left, s.stats_icon_rect.top, s.stats_icon_rect.right,
      s.stats_icon_rect.bottom, 4);
  s.x = s.portrait_rect.right + s.spacing;
  s.y = s.portrait_rect.top;
  s.control = GetDlgItem(hwnd, 0x70d);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  SetWindowPos(s.control, NULL, s.x, s.y, s.text_size.cx, s.line_height, 4);
  s.secondary_y = s.y;
  s.y += s.line_height + 2;
  s.control = GetDlgItem(hwnd, 0x6f0);
  s.control_width = __min(s.client_rect.right - s.x, s.character_width * 0xe);
  SetWindowPos(s.control, NULL, s.x, s.y, s.control_width, s.edit_height, 4);
  s.secondary_x = s.character_width * 2 + s.control_width;
  s.control = GetDlgItem(hwnd, 0x736);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  SetWindowPos(s.control, NULL, s.x + s.secondary_x, s.secondary_y, s.text_size.cx, s.line_height, 4);
  s.control = GetDlgItem(hwnd, 0x737);
  GetWindowTextA(s.control, s.label_text, 100);
  s.control_width = __min(s.client_rect.right - s.x, s.character_width * 0xe);
  SetWindowPos(s.control, NULL, s.x + s.secondary_x, s.y, s.control_width, s.edit_height, 4);
  s.y += s.edit_height + (s.line_height * 2) / 3;
  s.control = GetDlgItem(hwnd, 0x70e);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  SetWindowPos(s.control, NULL, s.x, s.y, s.text_size.cx, s.line_height, 4);
  s.y += s.line_height + 2;
  s.control = GetDlgItem(hwnd, 0x6f3);
  s.control_width = __min(s.client_rect.right - s.x, s.character_width * 0x100);
  SetWindowPos(s.control, NULL, s.x, s.y, s.control_width, s.edit_height, 4);
  s.y += s.edit_height + (s.line_height * 2) / 3;
  s.control = GetDlgItem(hwnd, 0x738);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  SetWindowPos(s.control, NULL, s.x, s.y, s.text_size.cx, s.line_height, 4);
  s.y += s.line_height + 2;
  s.control = GetDlgItem(hwnd, 0x739);
  SetWindowPos(s.control, NULL, s.x, s.y, s.control_width, s.edit_height, 4);
  s.y += s.edit_height + (s.line_height * 2) / 3;
  s.control = GetDlgItem(hwnd, 0x70f);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  SetWindowPos(s.control, NULL, s.x, s.y, s.text_size.cx, s.line_height, 4);
  s.y += s.line_height + 2;
  s.control = GetDlgItem(hwnd, 0x6f1);
  SetWindowPos(s.control, NULL, s.x, s.y, s.control_width, s.edit_height * 2, 4);
  s.y += s.edit_height * 2 + s.line_height + 2;
  s.control = GetDlgItem(hwnd, 0x741);
  GetWindowRect(GetDlgItem(hwnd, 0x741), &s.control_rect);
  MapWindowPoints(NULL, hwnd, (LPPOINT)&s.control_rect, 2);
  s.control_width = s.portrait_rect.right - s.portrait_rect.left;
  s.control_height = s.control_rect.bottom - s.control_rect.top;
  SetWindowPos(s.control, NULL, s.client_rect.right - s.control_width, s.y, s.control_width, s.control_height, 4);
  s.control = GetDlgItem(hwnd, 0x742);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  s.secondary_x = s.client_rect.right - (s.text_size.cx + s.spacing);
  s.secondary_y = s.client_rect.bottom - ((s.button_height * 3) / 2 + 5);
  SetWindowPos(s.control, NULL, s.secondary_x, s.secondary_y, s.text_size.cx + s.spacing, s.button_height, 4);
  s.control = GetDlgItem(hwnd, 0x717);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  s.secondary_x = s.client_rect.right - (s.text_size.cx + s.spacing);
  s.secondary_y = s.client_rect.bottom - s.button_height / 2;
  SetWindowPos(s.control, NULL, s.secondary_x, s.secondary_y, s.text_size.cx + s.spacing, s.button_height, 4);
  s.secondary_y += s.button_height * -2;
  s.y = s.portrait_rect.bottom;
  s.control = GetDlgItem(hwnd, 0x6f7);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  SetWindowPos(s.control, NULL, s.portrait_rect.left + 3, (s.y - s.edit_height) + -1,
      s.text_size.cx + s.spacing / 2, s.edit_height, 4);
  s.control = GetDlgItem(hwnd, 0x6f6);
  SetWindowPos(s.control, NULL, (s.portrait_rect.right - (s.text_size.cx + s.spacing / 2)) + -1,
      (s.y - s.edit_height) + -1, s.text_size.cx + s.spacing / 2, s.edit_height, 4);
  s.y = s.portrait_rect.bottom + s.line_height / 2;
  s.control = GetDlgItem(hwnd, 0x711);
  GetWindowRect(GetDlgItem(hwnd, 0x711), &s.control_rect);
  MapWindowPoints(NULL, hwnd, (LPPOINT)&s.control_rect, 2);
  s.control_width = s.portrait_rect.right - s.portrait_rect.left;
  s.control_height = s.control_rect.bottom - s.control_rect.top;
  GetWindowRect(GetDlgItem(hwnd, 0x6f7), &s.control_rect);
  MapWindowPoints(NULL, hwnd, (LPPOINT)&s.control_rect, 2);
  SetWindowPos(s.control, NULL, s.portrait_rect.left, s.y, s.control_width, s.control_height, 4);
  s.y += s.edit_height * 2;
  s.x = 0;
  s.control = GetDlgItem(hwnd, 0x73a);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  s.control_width = s.spacing * 2 + s.text_size.cx;
  SetWindowPos(s.control, NULL, s.x, s.y, s.control_width, s.line_height, 4);
  s.secondary_y = s.y + s.edit_height;
  s.control = GetDlgItem(hwnd, 0x73b);
  GetWindowTextA(s.control, s.label_text, 100);
  s.control_width = s.spacing * 2 + s.text_size.cx;
  SetWindowPos(s.control, NULL, s.x, s.secondary_y, s.control_width, s.line_height, 4);
  s.secondary_x = (s.client_rect.right * 2) / 5;
  s.control = GetDlgItem(hwnd, 0x73e);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  s.control_width = s.spacing * 2 + s.text_size.cx;
  SetWindowPos(s.control, NULL, s.secondary_x, s.y, s.control_width, s.line_height, 4);
  s.control = GetDlgItem(hwnd, 0x73f);
  GetWindowTextA(s.control, s.label_text, 100);
  s.control_width = s.spacing * 2 + s.text_size.cx;
  SetWindowPos(s.control, NULL, s.secondary_x, s.secondary_y, s.control_width, s.line_height, 4);
  s.y += s.edit_height * 3;
  s.x = 0;
  s.control = GetDlgItem(hwnd, 0x73c);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  s.control_width = s.spacing * 2 + s.text_size.cx;
  SetWindowPos(s.control, NULL, s.x, s.y, s.control_width, s.line_height, 4);
  s.secondary_y = s.y + s.edit_height;
  s.control = GetDlgItem(hwnd, 0x73d);
  GetWindowTextA(s.control, s.label_text, 100);
  s.control_width = s.spacing * 2 + s.text_size.cx;
  SetWindowPos(s.control, NULL, s.x, s.secondary_y, s.control_width, s.line_height, 4);
  s.secondary_x = (s.client_rect.right * 2) / 5;
  s.control = GetDlgItem(hwnd, 0x716);
  GetWindowTextA(s.control, s.label_text, 100);
  GetTextExtentPoint32A(s.dc, s.label_text, strlen(s.label_text), &s.text_size);
  s.control_width = s.spacing * 2 + s.text_size.cx;
  SetWindowPos(s.control, NULL, s.secondary_x, s.y, s.control_width, s.line_height, 4);
  ReleaseDC(hwnd, s.dc);
}
