#include "mystdbool.h"
#include "filtermenus.h"

enum Restriction
{
  RST_0 = 0x0,
  RST_ANTE = 0x1,
  RST_RESTRICTED = 0x2,
  RST_BANNED = 0x4,
};

typedef struct Restriction_t
{
  csvid_t csvid;
  int restriction;
} Restriction;

// GLOBAL: DECKDLL 0x10033278
// GLOBAL: MAGIC 0x0057a4f8
const Restriction restrictions[] =
    {
        {CARD_ID_AMULET_OF_QUOZ, RST_ANTE | RST_BANNED},
        {CARD_ID_BRONZE_TABLET, RST_ANTE | RST_BANNED},
        {CARD_ID_CONTRACT_FROM_BELOW, RST_ANTE | RST_BANNED},
        {CARD_ID_DARKPACT, RST_ANTE | RST_BANNED},
        {CARD_ID_DEMONIC_ATTORNEY, RST_ANTE | RST_BANNED},
        {CARD_ID_JEWELED_BIRD, RST_ANTE | RST_BANNED},
        {CARD_ID_REBIRTH, RST_ANTE | RST_BANNED},
        {CARD_ID_TEMPEST_EFREET, RST_ANTE | RST_BANNED},
        {CARD_ID_TIMMERIAN_FIENDS, RST_ANTE | RST_BANNED},

        {CARD_ID_ANCESTRAL_RECALL, RST_RESTRICTED},
        {CARD_ID_BALANCE, RST_RESTRICTED},
        {CARD_ID_BLACK_LOTUS, RST_RESTRICTED},
        {CARD_ID_BRAINSTORM, RST_RESTRICTED},
        {CARD_ID_CHALICE_OF_THE_VOID, RST_RESTRICTED},
        {CARD_ID_CHANNEL, RST_RESTRICTED},
        {CARD_ID_DEMONIC_CONSULTATION, RST_RESTRICTED},
        {CARD_ID_DEMONIC_TUTOR, RST_RESTRICTED},
        {CARD_ID_DIG_THROUGH_TIME, RST_RESTRICTED},
        {CARD_ID_FASTBOND, RST_RESTRICTED},
        {CARD_ID_FLASH, RST_RESTRICTED},
        {CARD_ID_IMPERIAL_SEAL, RST_RESTRICTED},
        {CARD_ID_LIBRARY_OF_ALEXANDRIA, RST_RESTRICTED},
        {CARD_ID_LIONS_EYE_DIAMOND, RST_RESTRICTED},
        {CARD_ID_LODESTONE_GOLEM, RST_RESTRICTED},
        {CARD_ID_LOTUS_PETAL, RST_RESTRICTED},
        {CARD_ID_MANA_CRYPT, RST_RESTRICTED},
        {CARD_ID_MANA_VAULT, RST_RESTRICTED},
        {CARD_ID_MEMORY_JAR, RST_RESTRICTED},
        {CARD_ID_MERCHANT_SCROLL, RST_RESTRICTED},
        {CARD_ID_MINDS_DESIRE, RST_RESTRICTED},
        {CARD_ID_MOX_EMERALD, RST_RESTRICTED},
        {CARD_ID_MOX_JET, RST_RESTRICTED},
        {CARD_ID_MOX_PEARL, RST_RESTRICTED},
        {CARD_ID_MOX_RUBY, RST_RESTRICTED},
        {CARD_ID_MOX_SAPPHIRE, RST_RESTRICTED},
        {CARD_ID_MYSTICAL_TUTOR, RST_RESTRICTED},
        {CARD_ID_NECROPOTENCE, RST_RESTRICTED},
        {CARD_ID_PONDER, RST_RESTRICTED},
        {CARD_ID_SOL_RING, RST_RESTRICTED},
        {CARD_ID_STRIP_MINE, RST_RESTRICTED},
        {CARD_ID_TIME_VAULT, RST_RESTRICTED},
        {CARD_ID_TIME_WALK, RST_RESTRICTED},
        {CARD_ID_TIMETWISTER, RST_RESTRICTED},
        {CARD_ID_TINKER, RST_RESTRICTED},
        {CARD_ID_TOLARIAN_ACADEMY, RST_RESTRICTED},
        {CARD_ID_TREASURE_CRUISE, RST_RESTRICTED},
        {CARD_ID_TRINISPHERE, RST_RESTRICTED},
        {CARD_ID_VAMPIRIC_TUTOR, RST_RESTRICTED},
        {CARD_ID_WHEEL_OF_FORTUNE, RST_RESTRICTED},
        {CARD_ID_WINDFALL, RST_RESTRICTED},
        {CARD_ID_YAWGMOTHS_BARGAIN, RST_RESTRICTED},
        {CARD_ID_YAWGMOTHS_WILL, RST_RESTRICTED},

        {CARD_ID_CHAOS_ORB, RST_BANNED},
        {CARD_ID_FALLING_STAR, RST_BANNED},
        {CARD_ID_SHAHRAZAD, RST_BANNED},

        {CARD_ID_CONSPIRACY_ADVANTAGEOUS_PROCLAMATION, RST_BANNED},
        {CARD_ID_CONSPIRACY_BACKUP_PLAN, RST_BANNED},
        {CARD_ID_CONSPIRACY_BRAGOS_FAVOR, RST_BANNED},
        {CARD_ID_CONSPIRACY_DOUBLE_STROKE, RST_BANNED},
        {CARD_ID_CONSPIRACY_IMMEDIATE_ACTION, RST_BANNED},
        {CARD_ID_CONSPIRACY_ITERATIVE_ANALYSIS, RST_BANNED},
        {CARD_ID_CONSPIRACY_MUZZIOS_PREPARATIONS, RST_BANNED},
        {CARD_ID_CONSPIRACY_POWER_PLAY, RST_BANNED},
        {CARD_ID_CONSPIRACY_SECRETS_OF_PARADISE, RST_BANNED},
        {CARD_ID_CONSPIRACY_SECRET_SUMMONING, RST_BANNED},
        {CARD_ID_CONSPIRACY_SENTINEL_DISPATCH, RST_BANNED},
        {CARD_ID_CONSPIRACY_UNEXPECTED_POTENTIAL, RST_BANNED},
        {CARD_ID_CONSPIRACY_WORLDKNIT, RST_BANNED},

        {CARD_ID_AIR_ELEMENTAL, RST_0},
};

// FUNCTION: DECKDLL 0x1001013d
// FUNCTION: MAGIC 0x004e0291
bool check_restricted(csvid_t csvid)
{
  int i;

  for (i = 0; i < 35; ++i)
    if (restrictions[i].csvid == csvid && (restrictions[i].restriction & RST_RESTRICTED))
      return true;
  return false;
}

// FUNCTION: DECKDLL 0x1001019e
// FUNCTION: MAGIC 0x004e02f6
bool check_banned(csvid_t csvid)
{
  int i;

  for (i = 0; i < 35; ++i)
    if (restrictions[i].csvid == csvid && (restrictions[i].restriction & RST_BANNED))
      return true;
  return false;
}

// FUNCTION: DECKDLL 0x100101ff
// FUNCTION: MAGIC 0x004e035b
bool check_ante(csvid_t csvid)
{
  int i;

  for (i = 0; i < 35; ++i)
    if (restrictions[i].csvid == csvid && (restrictions[i].restriction & RST_ANTE))
      return true;
  return false;
}

// FUNCTION: DECKDLL 0x100100e6
// FUNCTION: MAGIC 0x004e0225
bool check_basic(csvid_t csvid)
{
  if (csvid == CARD_ID_SWAMP ||
      csvid == CARD_ID_ISLAND ||
      csvid == CARD_ID_FOREST ||
      csvid == CARD_ID_MOUNTAIN ||
      csvid == CARD_ID_PLAINS)
    return true;

  return false;
}
